from functools import lru_cache


MODEL_NAME = "all-MiniLM-L6-v2"

@lru_cache(maxsize=1)
def _get_model():
    """Load the embedding model on first use, not while importing the API."""
    from sentence_transformers import SentenceTransformer

    return SentenceTransformer(MODEL_NAME)


def embed_chunks(chunks):
    """
    Generate embeddings for policy chunks.

    Uses the enriched EmbeddingText generated by markdown_chunker.py
    instead of embedding only the raw Content.
    """

    if not chunks:
        return []

    embedding_texts = []

    for chunk in chunks:
        # Prefer enriched embedding text
        text = chunk.get("EmbeddingText")

        # Fallback for old chunks
        if not text:
            text = chunk.get("Content", "")

        embedding_texts.append(text)

    embeddings = _get_model().encode(
        embedding_texts,
        convert_to_numpy=True,
        normalize_embeddings=True,
    )

    for chunk, embedding in zip(chunks, embeddings):
        chunk["embedding"] = embedding.tolist()

    return chunks
